config/routes.rb
Rails.application.routes.draw do
  resources :comments,only:[:create,:destroy]
  resources :answers,only:[:create,:destroy]
  resources :questions,only:[:create,:destroy]
  get 'home/index'

  devise_for :users
  devise_for :views
  get 'home/index'
  root 'home#index'
  get 'home/question'
  get '/ajax' => 'home#ajax'
  post '/toggleq'=> 'downvote#toggleq'

  post '/toggle' => 'upvote#toggle'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments,dependent: :destroy
  validates :content, presence: true

 
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :answer
  belongs_to :user
  validates :content, presence: true

end

app/models/downvotea.rb
class Downvotea < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
end

app/models/downvoteq.rb
class Downvoteq < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :downvoteqs
  has_many :upvote_qs
  validates :content, presence: true




  def upvote_by user_id
  	UpvoteQ.where(question_id: id, user_id: user_id).length > 0
  end



  def upvote_string user_id
  	if upvote_by user_id
  		return "devote"
  	else
  		return "Upvote"
  	end

  end


end

app/models/upvote_a.rb
class UpvoteA < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
end

app/models/upvote_q.rb
class UpvoteQ < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :question
         has_many :upvotes 
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)
    if current_user
      @answer.user_id = current_user.id
    
    end

    @question=Question.find(@answer.question_id)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to '/', notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
        format.js{   }
      else
        format.html { render 'home/index' }
        format.js{  }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:content, :user_id, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


        before_filter :configure_permitted_parameters, if: :devise_controller?

   protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password] )
            devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name,:email, :password] )
        end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]


  def create
    @comment = Comment.new(comment_params)
    @comment.user_id=current_user.id
   @answer=Answer.find(@comment.answer_id)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to '/', notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js{ }
      else
        format.html { render 'home/index' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :answer_id, :user_id)
    end
end

app/controllers/downvote_controller.rb
class DownvoteController < ApplicationController
			before_action :authenticate_user!

	def toggleq
			@question = Question.find(params[:question_id])
			downvoteq = Downvoteq.where(user: current_user, question: @question).first
		if downvoteq
			downvoteq.destroy!
			@isdownvote=false
				
		else
			Downvoteq.create(user: current_user, question: @question)
			@isdownvote=true
			
		end

		respond_to do |format|
			format.js{}
		end

	end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	@question = Question.new
  	@questionfeed=Question.all.order(created_at: :desc)
  	# @answer=Answer.new
  	@answerfeed=Answer.all.order(created_at: :desc)

  end


  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  
  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    # @answer=Answer.new
    respond_to do |format|
      if @question.save
        format.html { redirect_to '/', notice: 'Question was successfully created.' }
                format.js{}

        format.json { render :show, status: :created, location: @question }
      else 
        format.html { render 'home/index' }
        format.js{}
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :user_id)
    end
end

app/controllers/upvote_controller.rb
class UpvoteController < ApplicationController
	before_action :authenticate_user!
  def toggle
  		
		@question = Question.find(params[:question_id])
		upvoteq = UpvoteQ.where(user: current_user, question: @question).first
		if upvoteq
			upvoteq.destroy!
			@isupvote=false
				
		else
			UpvoteQ.create(user: current_user, question: @question)
			@isupvote=true
			
		end

		respond_to do |format|
			format.js{}
		end

  end





end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/downvote_helper.rb
module DownvoteHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/upvote_helper.rb
module UpvoteHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.text_field :question_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/create.js.erb
<% if @answer.errors.any?%>
noty({text: "<%=@answer.errors.full_messages.first%>", type: 'error'});
<%else%>

noty({text: 'answer was posted', type: 'alert'});
$('#answer_<%=@question.id%>').append("<%= escape_javascript (render 'home/answer', showanswer: @answer) %>");
$('#answer_content_<%=@question.id%>').val("");

// ,answers: @answers
<%end%>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Answers</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.content %></td>
        <td><%= answer.user %></td>
        <td><%= answer.question %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :answer_id %><br>
    <%= f.text_field :answer_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.errors.any?%>
noty({text: "<%=@comment.errors.full_messages.first%>", type: 'error'});
<%else%>

noty({text: 'comment added', type: 'alert',timeout:1000});
$('#comment_<%=@answer.id%>').append("<%= escape_javascript (render 'home/comment', comment:@comment) %>");
$('#comment_content_<%=@answer.id%>').val("");
<%end%>
// ,answers: @answers

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Answer</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.answer %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @comment.answer %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/create.js.erb
<% if @question.errors.any?%>
noty({text: "<%=@question.errors.full_messages.first%>", type: 'error'});
<%else%>
noty({text: 'question was posted', type: 'alert'});
$('#allq').prepend("<%= escape_javascript (render 'home/question', question: @question) %>");
$('#question_content').val("");
<%end%>
// ,answers: @answers

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td><%= question.user %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @question.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @question.user %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>